Repository Obsidian-TTRPG-Community/13th-Age-SRD-Markdown, pull requests merged in 2023-05, with the labels that each got.

#10 Tweaks
  README.md
Labels: Augmentation

#24 Fix: Update release-drafter.yml
  .github/release-drafter.yml
Labels: Patch

#26 Add statblocks for the Purple Dragon
  Monsters-Reference/Dragon/The Purple Dragon/Purple Dragon Common Abilities.md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Adventurer, Dragon form).md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Adventurer, Human form).md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Champion, Dragon Form).md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Champion, Human Form).md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Epic, Dragon Form).md
  Monsters-Reference/Dragon/The Purple Dragon/The Purple Dragon (Epic, Human Form).md
Labels: Conjure Enhancement

#28 feat(Monsters) Add Gibbering Mouthers, Hellwarped Beasts, Horned Azin…
  Monsters-Reference/Aberration/Gibbering Mouthers/Atrocious Gibbering Mouther.md
  Monsters-Reference/Aberration/Gibbering Mouthers/Gibbering Mouther.md
  Monsters-Reference/Aberration/Gibbering Mouthers/Gibbering Mouthers.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Beast.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Brute.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Spawn.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth Adult.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth Calf.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth.md
  Monsters-Reference/Beast/Kohwa/Kohwa Enforcer.md
  Monsters-Reference/Beast/Kohwa/Kohwa Messenger.md
  Monsters-Reference/Beast/Kohwa/Kohwa.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Beautific Gargoyle.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Hallowed Gargoyle.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Hallowed Gargoyles.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Temple Lion.md
  Monsters-Reference/Construct/Hellstone Gargoyle.md
  Monsters-Reference/Devil/Hellcats/Ember Imp.md
  Monsters-Reference/Devil/Hellcats/Hellcat.md
  Monsters-Reference/Monsters-Reference.md
  Monsters-Reference/Undead/Ghosts/Disgraced Legionnaire.md
  Monsters-Reference/Undead/Ghosts/Epic Haunting.md
  Monsters-Reference/Undead/Ghosts/Ghosts.md
  Monsters-Reference/Undead/Ghosts/Hungry Mouth Ghost.md
  Monsters-Reference/Undead/Ghosts/Lesser Haunting.md
  Monsters-Reference/Undead/Ghosts/Major Haunting.md
  Monsters-Reference/Undead/Ghosts/Most Hungry Ghost.md
  Monsters-Reference/Undead/Ghosts/Petulant Never-Was.md
  Monsters-Reference/Undead/Ghosts/Sadsack.md
  Monsters-Reference/Undead/Ghosts/Twisted Soul.md
  Monsters/Monsters.md
Labels: Patch

#29 Feat(Monsters) - Additional Monsters G-J
  Monsters-Reference/Aberration/Gibbering Mouthers/Atrocious Gibbering Mouther.md
  Monsters-Reference/Aberration/Gibbering Mouthers/Gibbering Mouther.md
  Monsters-Reference/Aberration/Gibbering Mouthers/Gibbering Mouthers.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Beast.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Brute.md
  Monsters-Reference/Aberration/Hellwarped Beast/Hellwarped Spawn.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth Adult.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth Calf.md
  Monsters-Reference/Beast/Horned Azinth/Horned Azinth.md
  Monsters-Reference/Beast/Kohwa/Kohwa Enforcer.md
  Monsters-Reference/Beast/Kohwa/Kohwa Messenger.md
  Monsters-Reference/Beast/Kohwa/Kohwa.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Beautific Gargoyle.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Hallowed Gargoyle.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Hallowed Gargoyles.md
  Monsters-Reference/Construct/Hallowed Gargoyles/Temple Lion.md
  Monsters-Reference/Construct/Hellstone Gargoyle.md
  Monsters-Reference/Devil/Hellcats/Ember Imp.md
  Monsters-Reference/Devil/Hellcats/Hellcat.md
  Monsters-Reference/Monsters-Reference.md
  Monsters-Reference/Undead/Ghosts/Disgraced Legionnaire.md
  Monsters-Reference/Undead/Ghosts/Epic Haunting.md
  Monsters-Reference/Undead/Ghosts/Ghosts.md
  Monsters-Reference/Undead/Ghosts/Hungry Mouth Ghost.md
  Monsters-Reference/Undead/Ghosts/Lesser Haunting.md
  Monsters-Reference/Undead/Ghosts/Major Haunting.md
  Monsters-Reference/Undead/Ghosts/Most Hungry Ghost.md
  Monsters-Reference/Undead/Ghosts/Petulant Never-Was.md
  Monsters-Reference/Undead/Ghosts/Sadsack.md
  Monsters-Reference/Undead/Ghosts/Twisted Soul.md
  Monsters/Monsters.md
Labels: Patch
